// <auto-generated />
using Lab4.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lab4.Migrations
{
    [DbContext(typeof(EducationContext))]
    [Migration("20220604204306_Update")]
    partial class Update
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CarPartSeller", b =>
                {
                    b.Property<int>("ScPartsId")
                        .HasColumnType("integer")
                        .HasColumnName("sc_parts_id");

                    b.Property<int>("SellersID")
                        .HasColumnType("integer")
                        .HasColumnName("sellers_id");

                    b.HasKey("ScPartsId", "SellersID")
                        .HasName("pk_car_part_seller");

                    b.HasIndex("SellersID")
                        .HasDatabaseName("ix_car_part_seller_sellers_id");

                    b.ToTable("car_part_seller", (string)null);
                });

            modelBuilder.Entity("Lab4.Data.Models.CarPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BrandOfAuto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("brand_of_auto");

                    b.Property<string>("ModelOfAuto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model_of_auto");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Price")
                        .HasColumnType("integer")
                        .HasColumnName("price");

                    b.HasKey("Id")
                        .HasName("pk_car_parts");

                    b.ToTable("car_parts", (string)null);
                });

            modelBuilder.Entity("Lab4.Data.Models.Customer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("grade");

                    b.HasKey("ID")
                        .HasName("pk_customers");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("Lab4.Data.Models.Seller", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fullname");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("grade");

                    b.Property<int>("NumOfSales")
                        .HasColumnType("integer")
                        .HasColumnName("num_of_sales");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("position");

                    b.HasKey("ID")
                        .HasName("pk_sellers");

                    b.ToTable("sellers", (string)null);
                });

            modelBuilder.Entity("CarPartSeller", b =>
                {
                    b.HasOne("Lab4.Data.Models.CarPart", null)
                        .WithMany()
                        .HasForeignKey("ScPartsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_car_part_seller_car_parts_sc_parts_id");

                    b.HasOne("Lab4.Data.Models.Seller", null)
                        .WithMany()
                        .HasForeignKey("SellersID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_car_part_seller_sellers_sellers_id");
                });
#pragma warning restore 612, 618
        }
    }
}
